#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Smart Agriculture Watering System"
  https://create.arduino.cc/cloud/things/1534400d-4703-42d7-bcbd-cb273ffc80df 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int sm_sensor1;
  int sm_sensor2;
  bool esp32_relay1;
  bool esp32_relay2;
  bool esp32_waterpump;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int relay1=4;
int relay2=16;
int soil_sensor1=33;
int soil_sensor2=34;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  pinMode(relay1,OUTPUT);
  pinMode(relay2,OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
sm_sensor1=analogRead(soil_sensor1);
delay(500);
sm_sensor2=analogRead(soil_sensor2);
delay(500);
// soil moisture 1
if(sm_sensor1>600){
  digitalWrite(relay1,LOW);
}
else{
  digitalWrite(relay1,HIGH);
}

//soil moisture 2
if(sm_sensor2>600){
  digitalWrite(relay2,LOW);
}
else{
  digitalWrite(relay2,HIGH);
}

}

/*
  Since Esp32Relay1 is READ_WRITE variable, onEsp32Relay1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEsp32Relay1Change()  {
  // Add your code here to act upon Esp32Relay1 change
  if(esp32_relay1){
    digitalWrite(relay1,LOW);
  }
  else{
    digitalWrite(relay1,HIGH);
  }
}
/*
  Since Esp32Relay2 is READ_WRITE variable, onEsp32Relay2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEsp32Relay2Change()  {
  // Add your code here to act upon Esp32Relay2 change
  if(esp32_relay2){
    digitalWrite(relay2,LOW);
  }
  else{
    digitalWrite(relay2,HIGH);
  }
}

/*
  Since Esp32Waterpump is READ_WRITE variable, onEsp32WaterpumpChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onEsp32WaterpumpChange()  {
  // Add your code here to act upon Esp32Waterpump change
}